# fly.toml app configuration file generated for listen-redis-falling-cherry-496 on 2025-02-17T15:25:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'listen-redis-falling-cherry-496'
primary_region = 'waw'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'redis_data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 6379

  [[services.ports]]
    port = 6379

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
